import {
  FullPatientRecord,
  MedicalDocument,
  LabObservation,
  Medication,
  MedicalCondition,
  ClinicalConflict,
  PatientSummaryData,
} from "@/types/clinical";
import { MANDATORY_SAFETY_DISCLAIMER } from "../clinical/safety-guardrails";

export const DEMO_PATIENT: FullPatientRecord = {
  isDemoMode: true,
  patient: {
    id: "patient-eleanor-vance",
    mrn: "MRN-90281-DEMO",
    fullName: "Eleanor Vance (Fictional Demo Patient)",
    dob: "1964-03-15",
    age: 62,
    gender: "Female",
    bloodGroup: "A+",
    knownAllergies: ["Penicillin (Severe Rash/Anaphylaxis)", "Sulfa Antibiotics"],
    chronicConditions: [
      "Type 2 Diabetes Mellitus",
      "Essential Hypertension",
      "Mild Chronic Kidney Disease (Stage 2)",
    ],
    primaryCarePhysician: "Dr. Sarah Jenkins, MD",
    isDemoPatient: true,
    createdAt: "2026-01-10T08:00:00.000Z",
    updatedAt: "2026-07-05T14:30:00.000Z",
  },
  documents: [
    {
      id: "doc-cmp-2026",
      patientId: "patient-eleanor-vance",
      filename: "MetroGen_Comprehensive_Metabolic_Panel_June2026.pdf",
      fileType: "application/pdf",
      fileUrl: "/demo-data/MetroGen_Comprehensive_Metabolic_Panel_June2026.pdf",
      documentType: "LAB_REPORT",
      reportDate: "2026-06-12",
      facilityName: "Metro General Pathology Laboratories",
      processingStatus: "COMPLETED",
      pageCount: 2,
      uploadedAt: "2026-06-12T10:15:00.000Z",
      isFictionalDemo: true,
      rawText: `METRO GENERAL PATHOLOGY LABORATORIES
CLINICAL BIOCHEMISTRY & METABOLIC REPORT
Patient: Eleanor Vance | DOB: 03/15/1964 | MRN: 90281
Ordering Physician: Dr. Sarah Jenkins, MD | Collected: 06/12/2026 07:30 AM

TEST NAME                     RESULT      UNITS      REF RANGE       FLAG
-------------------------------------------------------------------------
Fasting Blood Glucose         168         mg/dL      70 - 99         HIGH
Hemoglobin A1c (HbA1c)        8.9         %          4.0 - 5.6       HIGH
Serum Creatinine              1.85        mg/dL      0.60 - 1.20     HIGH
Blood Urea Nitrogen (BUN)     28          mg/dL      7 - 20          HIGH
eGFR (CKD-EPI)                38          mL/min     > 60            LOW
Serum Sodium                  139         mmol/L     135 - 145       NORMAL
Serum Potassium               4.6         mmol/L     3.5 - 5.1       NORMAL
Total Calcium                 9.2         mg/dL      8.5 - 10.2      NORMAL
Total Cholesterol             218         mg/dL      125 - 200       HIGH
Triglycerides                 195         mg/dL      50 - 150        HIGH
HDL Cholesterol               44          mg/dL      > 50            LOW
LDL Cholesterol (calc)        135         mg/dL      < 100           HIGH
-------------------------------------------------------------------------
Pathologist Comments: Marked worsening of glycemic index compared to Jan 2026.
Elevated serum creatinine with reduced eGFR (38) warrants clinical nephrology evaluation.`,
    },
    {
      id: "doc-cbc-2026",
      patientId: "patient-eleanor-vance",
      filename: "MetroGen_Complete_Blood_Count_June2026.pdf",
      fileType: "application/pdf",
      fileUrl: "/demo-data/MetroGen_Complete_Blood_Count_June2026.pdf",
      documentType: "LAB_REPORT",
      reportDate: "2026-06-12",
      facilityName: "Metro General Pathology Laboratories",
      processingStatus: "COMPLETED",
      pageCount: 1,
      uploadedAt: "2026-06-12T10:16:00.000Z",
      isFictionalDemo: true,
      rawText: `METRO GENERAL PATHOLOGY LABORATORIES
AUTOMATED HEMATOLOGY REPORT
Patient: Eleanor Vance | DOB: 03/15/1964 | MRN: 90281

TEST NAME                     RESULT      UNITS          REF RANGE       FLAG
-----------------------------------------------------------------------------
Hemoglobin (Hgb)              10.2        g/dL           12.0 - 16.0     LOW
Hematocrit (Hct)              31.4        %              36.0 - 48.0     LOW
Red Blood Cells (RBC)         3.62        x10^6/uL       4.00 - 5.40     LOW
White Blood Cells (WBC)       6.8         x10^3/uL       4.5 - 11.0      NORMAL
Platelets                     215         x10^3/uL       150 - 450       NORMAL
MCV                           78.5        fL             80.0 - 100.0    LOW
MCH                           25.8        pg             27.0 - 33.0     LOW
-----------------------------------------------------------------------------
Smear Interpretation: Microcytic, hypochromic red cell indices noted. Consistent with iron deficiency or anemia of chronic disease.`,
    },
    {
      id: "doc-rx-2026",
      patientId: "patient-eleanor-vance",
      filename: "StJude_Clinic_Discharge_Prescription_July2026.pdf",
      fileType: "application/pdf",
      fileUrl: "/demo-data/StJude_Clinic_Discharge_Prescription_July2026.pdf",
      documentType: "PRESCRIPTION",
      reportDate: "2026-07-04",
      facilityName: "St. Jude Ambulatory Family Care",
      processingStatus: "COMPLETED",
      pageCount: 1,
      uploadedAt: "2026-07-04T15:00:00.000Z",
      isFictionalDemo: true,
      rawText: `ST. JUDE AMBULATORY FAMILY CARE
DISCHARGE ORDERS & PRESCRIPTION SLIP
Patient: Eleanor Vance | Age: 62 | Date: 07/04/2026
Attending: Dr. Robert Miller, MD (Locum Tenens)

Rx ORDERS:
1. Amoxicillin 500mg
   Sig: Take 1 capsule by mouth three times daily for 7 days for dental abscess prophylaxis.
2. Metformin HCl 1000mg
   Sig: Take 1 tablet by mouth twice daily with morning and evening meals.
3. Lisinopril 20mg
   Sig: Take 1 tablet by mouth once daily every morning.
4. Atorvastatin Calcium 40mg
   Sig: Take 1 tablet by mouth once daily at bedtime.`,
    },
  ],
  observations: [
    {
      id: "obs-glucose-1",
      patientId: "patient-eleanor-vance",
      documentId: "doc-cmp-2026",
      testName: "Fasting Blood Glucose",
      category: "DIABETES",
      value: "168",
      numericValue: 168,
      unit: "mg/dL",
      refRangeLow: 70,
      refRangeHigh: 99,
      refRangeText: "70 - 99 mg/dL",
      canonicalRange: "70 - 99 mg/dL",
      interpretation: "HIGH",
      isCritical: false,
      provenance: {
        documentId: "doc-cmp-2026",
        documentName: "MetroGen_Comprehensive_Metabolic_Panel_June2026.pdf",
        pageNumber: 1,
        sourceSnippet: "Fasting Blood Glucose         168         mg/dL      70 - 99         HIGH",
        confidenceScore: 0.98,
        extractionEngine: "PREDEFINED_DEMO_DATASET",
      },
      verificationStatus: "VERIFIED",
      verifiedBy: "Dr. Sarah Jenkins (PCP)",
      observedAt: "2026-06-12T07:30:00.000Z",
      notes: "Elevated fasting state",
    },
    {
      id: "obs-a1c-1",
      patientId: "patient-eleanor-vance",
      documentId: "doc-cmp-2026",
      testName: "Hemoglobin A1c (HbA1c)",
      category: "DIABETES",
      value: "8.9",
      numericValue: 8.9,
      unit: "%",
      refRangeLow: 4.0,
      refRangeHigh: 5.6,
      refRangeText: "4.0 - 5.6 %",
      canonicalRange: "4.0 - 5.6 %",
      interpretation: "HIGH",
      isCritical: false,
      provenance: {
        documentId: "doc-cmp-2026",
        documentName: "MetroGen_Comprehensive_Metabolic_Panel_June2026.pdf",
        pageNumber: 1,
        sourceSnippet: "Hemoglobin A1c (HbA1c)        8.9         %          4.0 - 5.6       HIGH",
        confidenceScore: 0.99,
        extractionEngine: "PREDEFINED_DEMO_DATASET",
      },
      verificationStatus: "VERIFIED",
      verifiedBy: "Dr. Sarah Jenkins (PCP)",
      observedAt: "2026-06-12T07:30:00.000Z",
      notes: "Up from 6.9% in Jan 2026 (+2.0% delta)",
    },
    {
      id: "obs-creat-1",
      patientId: "patient-eleanor-vance",
      documentId: "doc-cmp-2026",
      testName: "Serum Creatinine",
      category: "BIOCHEMISTRY",
      value: "1.85",
      numericValue: 1.85,
      unit: "mg/dL",
      refRangeLow: 0.60,
      refRangeHigh: 1.20,
      refRangeText: "0.60 - 1.20 mg/dL",
      canonicalRange: "0.6 - 1.2 mg/dL",
      interpretation: "HIGH",
      isCritical: false,
      provenance: {
        documentId: "doc-cmp-2026",
        documentName: "MetroGen_Comprehensive_Metabolic_Panel_June2026.pdf",
        pageNumber: 1,
        sourceSnippet: "Serum Creatinine              1.85        mg/dL      0.60 - 1.20     HIGH",
        confidenceScore: 0.99,
        extractionEngine: "PREDEFINED_DEMO_DATASET",
      },
      verificationStatus: "VERIFIED",
      verifiedBy: "Dr. Sarah Jenkins (PCP)",
      observedAt: "2026-06-12T07:30:00.000Z",
      notes: "Acute elevation from baseline 1.05 mg/dL",
    },
    {
      id: "obs-egfr-1",
      patientId: "patient-eleanor-vance",
      documentId: "doc-cmp-2026",
      testName: "eGFR",
      category: "BIOCHEMISTRY",
      value: "38",
      numericValue: 38,
      unit: "mL/min/1.73m2",
      refRangeLow: 60,
      refRangeHigh: 120,
      refRangeText: "> 60 mL/min",
      canonicalRange: "60 - 120 mL/min/1.73m2",
      interpretation: "LOW",
      isCritical: false,
      provenance: {
        documentId: "doc-cmp-2026",
        documentName: "MetroGen_Comprehensive_Metabolic_Panel_June2026.pdf",
        pageNumber: 1,
        sourceSnippet: "eGFR (CKD-EPI)                38          mL/min     > 60            LOW",
        confidenceScore: 0.97,
        extractionEngine: "PREDEFINED_DEMO_DATASET",
      },
      verificationStatus: "EXTRACTED",
      observedAt: "2026-06-12T07:30:00.000Z",
    },
    {
      id: "obs-hgb-1",
      patientId: "patient-eleanor-vance",
      documentId: "doc-cbc-2026",
      testName: "Hemoglobin",
      category: "HEMATOLOGY",
      value: "10.2",
      numericValue: 10.2,
      unit: "g/dL",
      refRangeLow: 12.0,
      refRangeHigh: 16.0,
      refRangeText: "12.0 - 16.0 g/dL",
      canonicalRange: "12.0 - 16.0 g/dL",
      interpretation: "LOW",
      isCritical: false,
      provenance: {
        documentId: "doc-cbc-2026",
        documentName: "MetroGen_Complete_Blood_Count_June2026.pdf",
        pageNumber: 1,
        sourceSnippet: "Hemoglobin (Hgb)              10.2        g/dL           12.0 - 16.0     LOW",
        confidenceScore: 0.99,
        extractionEngine: "PREDEFINED_DEMO_DATASET",
      },
      verificationStatus: "EXTRACTED",
      observedAt: "2026-06-12T07:30:00.000Z",
      notes: "Decline from 12.8 g/dL 6 months prior",
    },
    {
      id: "obs-wbc-1",
      patientId: "patient-eleanor-vance",
      documentId: "doc-cbc-2026",
      testName: "White Blood Cells",
      category: "HEMATOLOGY",
      value: "6.8",
      numericValue: 6.8,
      unit: "x10^3/uL",
      refRangeLow: 4.5,
      refRangeHigh: 11.0,
      refRangeText: "4.5 - 11.0 x10^3/uL",
      canonicalRange: "4.5 - 11.0 x10^3/uL",
      interpretation: "NORMAL",
      isCritical: false,
      provenance: {
        documentId: "doc-cbc-2026",
        documentName: "MetroGen_Complete_Blood_Count_June2026.pdf",
        pageNumber: 1,
        sourceSnippet: "White Blood Cells (WBC)       6.8         x10^3/uL       4.5 - 11.0      NORMAL",
        confidenceScore: 0.99,
        extractionEngine: "PREDEFINED_DEMO_DATASET",
      },
      verificationStatus: "EXTRACTED",
      observedAt: "2026-06-12T07:30:00.000Z",
    },
    {
      id: "obs-potassium-1",
      patientId: "patient-eleanor-vance",
      documentId: "doc-cmp-2026",
      testName: "Potassium",
      category: "BIOCHEMISTRY",
      value: "4.6",
      numericValue: 4.6,
      unit: "mmol/L",
      refRangeLow: 3.5,
      refRangeHigh: 5.1,
      refRangeText: "3.5 - 5.1 mmol/L",
      canonicalRange: "3.5 - 5.1 mmol/L",
      interpretation: "NORMAL",
      isCritical: false,
      provenance: {
        documentId: "doc-cmp-2026",
        documentName: "MetroGen_Comprehensive_Metabolic_Panel_June2026.pdf",
        pageNumber: 1,
        sourceSnippet: "Serum Potassium               4.6         mmol/L     3.5 - 5.1       NORMAL",
        confidenceScore: 0.98,
        extractionEngine: "PREDEFINED_DEMO_DATASET",
      },
      verificationStatus: "EXTRACTED",
      observedAt: "2026-06-12T07:30:00.000Z",
    },
    {
      id: "obs-ldl-1",
      patientId: "patient-eleanor-vance",
      documentId: "doc-cmp-2026",
      testName: "LDL Cholesterol",
      category: "LIPID",
      value: "135",
      numericValue: 135,
      unit: "mg/dL",
      refRangeLow: 50,
      refRangeHigh: 100,
      refRangeText: "< 100 mg/dL",
      canonicalRange: "50 - 100 mg/dL",
      interpretation: "HIGH",
      isCritical: false,
      provenance: {
        documentId: "doc-cmp-2026",
        documentName: "MetroGen_Comprehensive_Metabolic_Panel_June2026.pdf",
        pageNumber: 1,
        sourceSnippet: "LDL Cholesterol (calc)        135         mg/dL      < 100           HIGH",
        confidenceScore: 0.96,
        extractionEngine: "PREDEFINED_DEMO_DATASET",
      },
      verificationStatus: "EXTRACTED",
      observedAt: "2026-06-12T07:30:00.000Z",
    },
  ],
  medications: [
    {
      id: "med-amox-1",
      patientId: "patient-eleanor-vance",
      documentId: "doc-rx-2026",
      drugName: "Amoxicillin",
      dosage: "500 mg",
      frequency: "1 capsule 3 times daily for 7 days",
      route: "Oral",
      purpose: "Dental abscess prophylaxis",
      status: "ACTIVE",
      provenance: {
        documentId: "doc-rx-2026",
        documentName: "StJude_Clinic_Discharge_Prescription_July2026.pdf",
        pageNumber: 1,
        sourceSnippet: "1. Amoxicillin 500mg\n   Sig: Take 1 capsule by mouth three times daily for 7 days for dental abscess prophylaxis.",
        confidenceScore: 0.99,
        extractionEngine: "PREDEFINED_DEMO_DATASET",
      },
      verificationStatus: "EXTRACTED",
      prescribedDate: "2026-07-04",
      prescribingDoctor: "Dr. Robert Miller, MD",
    },
    {
      id: "med-metformin-1",
      patientId: "patient-eleanor-vance",
      documentId: "doc-rx-2026",
      drugName: "Metformin HCl",
      dosage: "1000 mg",
      frequency: "1 tablet twice daily with meals",
      route: "Oral",
      purpose: "Type 2 Diabetes glycemic control",
      status: "ACTIVE",
      provenance: {
        documentId: "doc-rx-2026",
        documentName: "StJude_Clinic_Discharge_Prescription_July2026.pdf",
        pageNumber: 1,
        sourceSnippet: "2. Metformin HCl 1000mg\n   Sig: Take 1 tablet by mouth twice daily with morning and evening meals.",
        confidenceScore: 0.98,
        extractionEngine: "PREDEFINED_DEMO_DATASET",
      },
      verificationStatus: "VERIFIED",
      verifiedBy: "Patient Self-Check",
      prescribedDate: "2026-07-04",
      prescribingDoctor: "Dr. Robert Miller, MD",
    },
    {
      id: "med-lisinopril-1",
      patientId: "patient-eleanor-vance",
      documentId: "doc-rx-2026",
      drugName: "Lisinopril",
      dosage: "20 mg",
      frequency: "1 tablet daily in the morning",
      route: "Oral",
      purpose: "Hypertension / renal protection",
      status: "ACTIVE",
      provenance: {
        documentId: "doc-rx-2026",
        documentName: "StJude_Clinic_Discharge_Prescription_July2026.pdf",
        pageNumber: 1,
        sourceSnippet: "3. Lisinopril 20mg\n   Sig: Take 1 tablet by mouth once daily every morning.",
        confidenceScore: 0.98,
        extractionEngine: "PREDEFINED_DEMO_DATASET",
      },
      verificationStatus: "VERIFIED",
      prescribedDate: "2026-07-04",
      prescribingDoctor: "Dr. Robert Miller, MD",
    },
    {
      id: "med-atorvastatin-1",
      patientId: "patient-eleanor-vance",
      documentId: "doc-rx-2026",
      drugName: "Atorvastatin Calcium",
      dosage: "40 mg",
      frequency: "1 tablet daily at bedtime",
      route: "Oral",
      purpose: "Dyslipidemia / cardiovascular risk reduction",
      status: "ACTIVE",
      provenance: {
        documentId: "doc-rx-2026",
        documentName: "StJude_Clinic_Discharge_Prescription_July2026.pdf",
        pageNumber: 1,
        sourceSnippet: "4. Atorvastatin Calcium 40mg\n   Sig: Take 1 tablet by mouth once daily at bedtime.",
        confidenceScore: 0.97,
        extractionEngine: "PREDEFINED_DEMO_DATASET",
      },
      verificationStatus: "EXTRACTED",
      prescribedDate: "2026-07-04",
      prescribingDoctor: "Dr. Robert Miller, MD",
    },
  ],
  conditions: [
    {
      id: "cond-t2d",
      patientId: "patient-eleanor-vance",
      documentId: "doc-cmp-2026",
      conditionName: "Type 2 Diabetes Mellitus with elevated glycemic index",
      status: "ACTIVE",
      provenance: {
        documentId: "doc-cmp-2026",
        documentName: "MetroGen_Comprehensive_Metabolic_Panel_June2026.pdf",
        pageNumber: 1,
        sourceSnippet: "Marked worsening of glycemic index compared to Jan 2026 (HbA1c 8.9%)",
        confidenceScore: 0.98,
        extractionEngine: "PREDEFINED_DEMO_DATASET",
      },
      verificationStatus: "VERIFIED",
      firstNotedDate: "2021-04-10",
    },
    {
      id: "cond-anemia",
      patientId: "patient-eleanor-vance",
      documentId: "doc-cbc-2026",
      conditionName: "Microcytic Hypochromic Anemia",
      status: "ACTIVE",
      provenance: {
        documentId: "doc-cbc-2026",
        documentName: "MetroGen_Complete_Blood_Count_June2026.pdf",
        pageNumber: 1,
        sourceSnippet: "Microcytic, hypochromic red cell indices noted (Hgb 10.2 g/dL, MCV 78.5 fL)",
        confidenceScore: 0.95,
        extractionEngine: "PREDEFINED_DEMO_DATASET",
      },
      verificationStatus: "EXTRACTED",
      firstNotedDate: "2026-06-12",
    },
    {
      id: "cond-renal",
      patientId: "patient-eleanor-vance",
      documentId: "doc-cmp-2026",
      conditionName: "Renal Function Decline (eGFR 38 mL/min)",
      status: "ACTIVE",
      provenance: {
        documentId: "doc-cmp-2026",
        documentName: "MetroGen_Comprehensive_Metabolic_Panel_June2026.pdf",
        pageNumber: 1,
        sourceSnippet: "Elevated serum creatinine with reduced eGFR (38) warrants clinical nephrology evaluation.",
        confidenceScore: 0.96,
        extractionEngine: "PREDEFINED_DEMO_DATASET",
      },
      verificationStatus: "EXTRACTED",
      firstNotedDate: "2026-06-12",
    },
  ],
  conflicts: [
    {
      id: "conflict-allergy-amox",
      patientId: "patient-eleanor-vance",
      type: "ALLERGY_MEDICATION_CONFLICT",
      severity: "CRITICAL",
      title: "Severe Contraindication: Amoxicillin Prescribed Despite Documented Penicillin Allergy",
      description: "Patient has documented severe allergy to 'Penicillin (Severe Rash/Anaphylaxis)', but received a discharge prescription for Amoxicillin 500 mg.",
      clinicalImplication: "Amoxicillin shares the beta-lactam bicyclic nucleus with Penicillin. Administering it to a penicillin-allergic patient carries severe risk of acute hypersensitivity or anaphylactic reaction.",
      suggestedDoctorQuestion: "I see Amoxicillin was prescribed for dental prophylaxis, but my chart records a severe Penicillin allergy. Should I hold this medication and receive an alternative non-penicillin antibiotic (e.g. Clindamycin or Azithromycin)?",
      involvedDocumentIds: ["doc-rx-2026"],
      involvedItems: ["Penicillin Allergy", "Amoxicillin 500mg"],
      resolutionStatus: "UNRESOLVED",
      detectedAt: "2026-07-04T15:05:00.000Z",
    },
    {
      id: "conflict-metformin-kidney",
      patientId: "patient-eleanor-vance",
      type: "DOSAGE_UNCERTAINTY",
      severity: "WARNING",
      title: "Medication Caution: Metformin 1000mg BID with Reduced eGFR (38 mL/min)",
      description: "Patient is prescribed maximum dose Metformin (1000mg BID) while recent metabolic labs demonstrate an eGFR of 38 mL/min and Serum Creatinine of 1.85 mg/dL.",
      clinicalImplication: "FDA clinical prescribing guidelines state that when eGFR falls between 30-44 mL/min, the maximum recommended Metformin dose is 1000mg daily (500mg BID), and initiation is not recommended due to increased risk of lactic acidosis.",
      suggestedDoctorQuestion: "My recent kidney lab showed an eGFR of 38 mL/min. Is my current dose of Metformin 1000mg twice daily still safe, or should my dose be halved or re-evaluated?",
      involvedDocumentIds: ["doc-cmp-2026", "doc-rx-2026"],
      involvedItems: ["Metformin 1000mg BID", "eGFR: 38 mL/min", "Creatinine: 1.85 mg/dL"],
      resolutionStatus: "UNRESOLVED",
      detectedAt: "2026-07-04T15:06:00.000Z",
    },
    {
      id: "conflict-trend-a1c",
      patientId: "patient-eleanor-vance",
      type: "LAB_TREND_ANOMALY",
      severity: "WARNING",
      title: "Significant HbA1c Elevation (+2.0% over 5 months)",
      description: "HbA1c increased from 6.9% (Baseline - Jan 2026) to 8.9% (Current - June 2026), alongside fasting blood glucose of 168 mg/dL.",
      clinicalImplication: "Represents a substantial loss of glycemic regulation over the preceding 90-120 days, putting the patient at increased risk of microvascular complications.",
      suggestedDoctorQuestion: "My HbA1c jumped from 6.9% up to 8.9%. What dietary changes or diabetes medication adjustments do you recommend to bring this back into target range?",
      involvedDocumentIds: ["doc-cmp-2026"],
      involvedItems: ["HbA1c: 6.9% -> 8.9%"],
      resolutionStatus: "UNRESOLVED",
      detectedAt: "2026-06-12T10:20:00.000Z",
    },
  ],
  latestSummary: {
    id: "sum-eleanor-demo",
    patientId: "patient-eleanor-vance",
    engineUsed: "PREDEFINED_DEMO_SYNTHESIS",
    overview: "Eleanor's recent medical records from June and July 2026 present three main areas requiring physician coordination: blood sugar management, kidney filtration changes, and an urgent medication safety check. Her three-month average blood sugar (HbA1c) was recorded at 8.9%, higher than typical targets. Her kidney lab tests show a reduced filtration rate (eGFR 38), and her red blood cell markers indicate mild anemia. Most urgently, a new prescription for Amoxicillin was issued despite her recorded penicillin allergy.",
    plainLanguageLabs: [
      {
        testName: "Hemoglobin A1c (8.9%)",
        whatItMeans: "Reflects the average sugar attached to red blood cells over the past 2-3 months.",
        patientStatus: "Above recommended target range (standard upper limit is 5.6%). Discuss diabetes management with your doctor.",
        isOutOfRange: true,
      },
      {
        testName: "Serum Creatinine (1.85 mg/dL) & eGFR (38)",
        whatItMeans: "Measures how effectively your kidneys are filtering natural waste from your bloodstream.",
        patientStatus: "Filtering capacity is lower than typical expected numbers (>60). This is important because certain medications rely on kidney clearance.",
        isOutOfRange: true,
      },
      {
        testName: "Hemoglobin (10.2 g/dL)",
        whatItMeans: "The protein in red blood cells that transports oxygen to your organs and muscles.",
        patientStatus: "Below normal adult female range (12.0 - 16.0 g/dL), indicating mild anemia which may contribute to feelings of fatigue.",
        isOutOfRange: true,
      },
      {
        testName: "Potassium (4.6 mmol/L)",
        whatItMeans: "Essential mineral for healthy heart rhythm and muscle contractions.",
        patientStatus: "Well within normal safe limits (3.5 - 5.1 mmol/L).",
        isOutOfRange: false,
      },
    ],
    questionsForDoctor: [
      {
        id: "q-1",
        question: "I was prescribed Amoxicillin, but my chart lists a severe Penicillin allergy. What alternative antibiotic should I take instead?",
        context: "Critical safety check: Amoxicillin is in the penicillin family.",
        priority: "HIGH",
      },
      {
        id: "q-2",
        question: "My kidney filtration rate (eGFR) is 38. Should my Metformin dose (currently 1000mg twice daily) be reduced or adjusted?",
        context: "Medication guidelines often recommend lowering Metformin doses when kidney filtration drops.",
        priority: "HIGH",
      },
      {
        id: "q-3",
        question: "My HbA1c rose from 6.9% to 8.9%. What is our target number and what steps should we take?",
        context: "Significant change over the past 5 months indicates a need for regimen review.",
        priority: "MEDIUM",
      },
      {
        id: "q-4",
        question: "My hemoglobin dropped to 10.2 g/dL with low cell size (MCV). Do you recommend testing my iron levels?",
        context: "Helps determine whether iron supplementation or nutritional adjustments are beneficial.",
        priority: "STANDARD",
      },
    ],
    clinicianBriefing: {
      chiefIssues: [
        "Glycemic excursion: HbA1c 8.9% (delta +2.0% vs Jan baseline)",
        "Renal compromise: Serum Creatinine 1.85 mg/dL, eGFR 38 mL/min/1.73m2",
        "Microcytic anemia: Hgb 10.2 g/dL, Hct 31.4%, MCV 78.5 fL",
      ],
      criticalValues: [
        "Acute contraindication: Amoxicillin 500mg Rx issued with documented Penicillin anaphylaxis",
        "Metformin 1000mg BID exceeds renal threshold for eGFR < 45",
      ],
      medicationRegimen: [
        "Amoxicillin 500mg TID (HOLD - Allergy conflict)",
        "Metformin 1000mg BID (Dose review indicated)",
        "Lisinopril 20mg daily",
        "Atorvastatin 40mg daily",
      ],
      discrepancyAlerts: [
        "Beta-lactam allergy cross-reactivity",
        "Renal clearance discordance with biguanide therapy",
      ],
    },
    safetyDisclaimer: MANDATORY_SAFETY_DISCLAIMER,
    generatedAt: "2026-07-04T15:15:00.000Z",
  },
};
